# Generated by Django 3.1.1 on 2021-05-27 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Scenes_name', models.CharField(max_length=100)),
                ('url', models.CharField(default='None', max_length=200)),
                ('db_name', models.CharField(max_length=100)),
                ('db_server', models.CharField(max_length=100)),
                ('test_zh', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('test_range', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=500)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='D_Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='None', max_length=200)),
                ('UA', models.CharField(default='None', max_length=200)),
                ('platform', models.CharField(default='None', max_length=200)),
                ('browserName', models.CharField(default='None', max_length=200)),
                ('version', models.CharField(default='None', max_length=200)),
                ('javascriptEnabled', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Element_operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_tap', models.CharField(max_length=2000)),
                ('op_Remarks', models.CharField(max_length=500)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='img_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='None', max_length=200)),
                ('text', models.CharField(default='None', max_length=200)),
                ('code', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='logic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logic_json', models.CharField(max_length=2000)),
                ('logic_Remarks', models.CharField(max_length=500)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='python_txt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('python_tap', models.CharField(max_length=2000)),
                ('python_Remarks', models.CharField(max_length=500)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='selenium_api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_api', models.CharField(max_length=2000)),
                ('api_Remarks', models.CharField(max_length=500)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Treegrid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('Rights_Groups', models.TextField()),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Treegrid_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urls', models.CharField(default='None', max_length=200)),
                ('urls_name', models.CharField(default='None', max_length=200)),
                ('T_id', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='None', max_length=200)),
                ('user_name', models.CharField(default='None', max_length=200)),
                ('password', models.CharField(default='None', max_length=200)),
                ('c_password', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('treegrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.treegrid')),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('run_status', models.SmallIntegerField(choices=[(1, 'open'), (2, 'off')], default=2, verbose_name='运行状态')),
                ('dict_case', models.CharField(max_length=2000)),
                ('execution_time', models.BigIntegerField(default=0)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('Config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.config')),
                ('D_Config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_config')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_status', models.SmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'pass')], default=3, verbose_name='结果状态')),
                ('result_json', models.CharField(max_length=2000)),
                ('Execution_time', models.CharField(max_length=32)),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('Scenes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=20)),
                ('Judgment_data', models.TextField()),
                ('Node_information', models.TextField()),
                ('process_data', models.TextField()),
                ('new_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Nailed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='None', max_length=200)),
                ('text', models.CharField(default='None', max_length=200)),
                ('messageUrl', models.CharField(default='None', max_length=200)),
                ('Nailed_url', models.CharField(default='None', max_length=200)),
                ('title', models.CharField(default='None', max_length=200)),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
        migrations.AddField(
            model_name='d_config',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='config',
            name='Nailed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nailed'),
        ),
        migrations.AddField(
            model_name='config',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
